"""SQL-backed quiz sessions and mastery history.

Set DATABASE_URL to hosted PostgreSQL in production. When it is unset, the same
schema uses local SQLite so development remains zero-configuration.
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from threading import RLock
from typing import Any, Dict, List

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine


class QuizAnalyticsStore:
    def __init__(self, engine: Engine | None = None) -> None:
        data_dir = Path(__file__).resolve().parent.parent / "data"
        data_dir.mkdir(parents=True, exist_ok=True)
        default_url = f"sqlite:///{(data_dir / 'analytics.sqlite3').as_posix()}"
        database_url = os.getenv("DATABASE_URL") or default_url
        if database_url.startswith("postgres://"):
            database_url = database_url.replace("postgres://", "postgresql+psycopg://", 1)
        elif database_url.startswith("postgresql://"):
            database_url = database_url.replace("postgresql://", "postgresql+psycopg://", 1)
        self.database_url = database_url
        self.engine: Engine = engine if engine is not None else create_engine(database_url, pool_pre_ping=True)
        self._lock = RLock()
        self._initialise()
        from .mistakes import MistakeNotebook
        self.mistakes = MistakeNotebook(self.engine, self._lock)

    @property
    def storage_backend(self) -> str:
        return "postgresql" if self.engine.dialect.name == "postgresql" else "sqlite"

    def _initialise(self) -> None:
        id_column = (
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.engine.dialect.name == "postgresql"
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        with self.engine.begin() as connection:
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS quiz_attempts (
                    id {id_column}, topic TEXT NOT NULL, completed_at TEXT NOT NULL,
                    score REAL NOT NULL, previous_mastery REAL NOT NULL,
                    new_mastery REAL NOT NULL, correct_count INTEGER NOT NULL,
                    question_count INTEGER NOT NULL, details_json TEXT NOT NULL
                )
            """))
            connection.execute(text("""
                CREATE TABLE IF NOT EXISTS generated_quizzes (
                    id TEXT PRIMARY KEY, topic TEXT NOT NULL, created_at TEXT NOT NULL,
                    questions_json TEXT NOT NULL
                )
            """))

    def save_quiz(self, topic: str, questions: List[Dict[str, Any]]) -> str:
        quiz_id = uuid.uuid4().hex
        with self._lock, self.engine.begin() as connection:
            connection.execute(text("""INSERT INTO generated_quizzes
                (id, topic, created_at, questions_json)
                VALUES (:id, :topic, :created_at, :questions_json)"""), {
                    "id": quiz_id, "topic": topic,
                    "created_at": datetime.now(timezone.utc).isoformat(),
                    "questions_json": json.dumps(questions),
                })
        return quiz_id

    def get_quiz(self, quiz_id: str) -> Dict[str, Any] | None:
        with self.engine.connect() as connection:
            row = connection.execute(
                text("SELECT topic, questions_json FROM generated_quizzes WHERE id = :id"),
                {"id": quiz_id},
            ).mappings().first()
        if not row:
            return None
        return {"topic": row["topic"], "questions": json.loads(row["questions_json"])}

    def record(self, topic: str, score: float, previous_mastery: float,
               new_mastery: float, correct_count: int, question_count: int,
               details: List[Dict[str, Any]]) -> int:
        values = {
            "topic": topic, "completed_at": datetime.now(timezone.utc).isoformat(),
            "score": score, "previous_mastery": previous_mastery,
            "new_mastery": new_mastery, "correct_count": correct_count,
            "question_count": question_count, "details_json": json.dumps(details),
        }
        sql = """INSERT INTO quiz_attempts (
            topic, completed_at, score, previous_mastery, new_mastery,
            correct_count, question_count, details_json
        ) VALUES (
            :topic, :completed_at, :score, :previous_mastery, :new_mastery,
            :correct_count, :question_count, :details_json
        )"""
        with self._lock, self.engine.begin() as connection:
            if self.engine.dialect.name == "postgresql":
                attempt_id = int(connection.execute(text(sql + " RETURNING id"), values).scalar_one())
            else:
                result = connection.execute(text(sql), values)
                attempt_id = int(result.lastrowid or 0)
            self.mistakes.capture(connection, attempt_id, topic, values['completed_at'], details)
            return attempt_id

    def history(self, topic: str, limit: int = 20) -> List[Dict[str, Any]]:
        with self.engine.connect() as connection:
            rows = connection.execute(text("""
                SELECT id, completed_at, score, previous_mastery, new_mastery
                FROM quiz_attempts WHERE topic = :topic ORDER BY id DESC LIMIT :limit
            """), {"topic": topic, "limit": limit}).mappings().all()
        return [dict(row) for row in reversed(rows)]

    def topic_summaries(self) -> List[Dict[str, Any]]:
        with self.engine.connect() as connection:
            rows = connection.execute(text("""
                SELECT topic, score, new_mastery, completed_at
                FROM quiz_attempts ORDER BY id ASC
            """)).mappings().all()
        grouped: Dict[str, Dict[str, Any]] = {}
        for row in rows:
            summary = grouped.setdefault(row["topic"], {
                "topic": row["topic"], "attempts": 0, "scores": [], "mastery_values": [],
            })
            summary["attempts"] += 1
            summary["scores"].append(float(row["score"]))
            summary["mastery_values"].append(float(row["new_mastery"]))
            summary["last_attempt_at"] = row["completed_at"]
        results = []
        for summary in grouped.values():
            mastery_values = summary.pop("mastery_values")
            scores = summary.pop("scores")
            summary["current_mastery"] = mastery_values[-1]
            summary["average_score"] = round(sum(scores) / len(scores), 1)
            summary["mastery_trend"] = round(
                mastery_values[-1] - mastery_values[-2], 1
            ) if len(mastery_values) > 1 else 0.0
            results.append(summary)
        return results

    def attempts(self, limit: int = 100) -> List[Dict[str, Any]]:
        with self.engine.connect() as connection:
            rows = connection.execute(text("""
                SELECT id, topic, completed_at, score, previous_mastery, new_mastery,
                       correct_count, question_count, details_json
                FROM quiz_attempts ORDER BY id DESC LIMIT :limit
            """), {"limit": limit}).mappings().all()
        return [{**dict(row), "details": json.loads(row["details_json"])} for row in rows]

    def delete_topics(self, topics: List[str]) -> Dict[str, int]:
        """Delete assessment state for topics whose indexed source was removed."""
        cleaned = sorted({str(topic).strip() for topic in topics if str(topic).strip()})
        deleted_attempts = 0
        deleted_quizzes = 0
        with self._lock, self.engine.begin() as connection:
            for topic in cleaned:
                connection.execute(text('DELETE FROM mistake_reviews WHERE topic=:topic'), {'topic': topic})
                attempts_result = connection.execute(
                    text("DELETE FROM quiz_attempts WHERE topic = :topic"),
                    {"topic": topic},
                )
                quizzes_result = connection.execute(
                    text("DELETE FROM generated_quizzes WHERE topic = :topic"),
                    {"topic": topic},
                )
                deleted_attempts += max(0, int(attempts_result.rowcount or 0))
                deleted_quizzes += max(0, int(quizzes_result.rowcount or 0))
        return {
            "quiz_attempts": deleted_attempts,
            "generated_quizzes": deleted_quizzes,
        }


quiz_analytics = QuizAnalyticsStore()
